AWSTemplateFormatVersion: '2010-09-09'
Description: Alexa State Games Stack
Metadata:
  Name: alexa-state-games
Outputs:
  AlexaSkillFunctionARN:
    Description: Paste this Lambda ARN into your skill endpoint
    Value:
      Fn::GetAtt:
      - askLambdaFunction
      - Arn
  DynamoDbTable:
    Value:
      Fn::Sub: ask${ProjectName}
  DynamoDbTableLeaderboard:
    Value:
      Fn::Sub: ask${ProjectName}Leaderboard
Parameters:
  ProjectName:
    Default: StateGames
    Type: String
Resources:
  DatabaseTable:
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName:
        Fn::Sub: ask${ProjectName}
    Type: AWS::Serverless::SimpleTable
  askLambdaFunction:
    Properties:
      CodeUri: s3://alexaconsole789/state-games-demo/f60174cfdafae6233fcc7b03c6a33205
      Description: Alexa Skill Lambda function
      Environment:
        Variables:
          DYNAMODB_TABLE:
            Fn::Sub: ask${ProjectName}
          DYNAMODB_TABLE_LEADERBOARD:
            Fn::Sub: ask${ProjectName}Leaderboard
      Events:
        AlexaTrigger:
          Type: AlexaSkill
      FunctionName:
        Fn::Sub: ask-custom-${ProjectName}
      Handler: index.handler
      MemorySize: 128
      Policies:
      - Statement:
        - Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
          Effect: Allow
          Resource:
          - Fn::Sub: arn:aws:dynamodb:*:*:table/ask${ProjectName}
        Version: '2012-10-17'
      Runtime: nodejs8.10
      Timeout: 7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
